development:
  database: server_development
  host: 127.0.0.1
  url: mongodb://127.0.0.1:27017

test:
  url: {{envOr "TEST_DATABASE_URL" "mongodb://127.0.0.1:27017"}}
  database: server_test

production:
  url: {{envOr "DATABASE_URL" "mongodb://127.0.0.1:27017"}}
  database: server_production
